version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb
    ports:
      - 5432:5432
    networks:
      - my_network

# a container for databas visualization
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - 8000:8080
#    networks:
#      - my_network

  selenium:
    image: selenium/standalone-chrome
    healthcheck:
      test: [ "CMD", "curl", "-s", "http://localhost:4444/wd/hub/status" ]
      interval: 20s
      timeout: 10s
      retries: 2
    ports:
      - 4444:4444
    networks:
      - my_network

  scrapy-selenium:
    build:
      context: .
    shm_size: 1gb
    depends_on:
      selenium:
        condition: service_healthy
      database:
        condition: service_started
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=exampledb
    networks:
      - my_network

  simple-server:
    image: python:3.9
    restart: always
    depends_on:
      - scrapy-selenium
      - database
    ports:
      - 8080:8080
    volumes:
      - ./simple_server.py:/app/simple_server.py
    command: ["sh", "-c", "pip install psycopg2-binary && python /app/simple_server.py"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
